global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    app: app/weps
    weps_prometheus: 1561-yuk-weps-admintwo-prometheus
rule_files:
  - /etc/prometheus/rules/prometheus-k8s-rulefiles-0/*.yaml
scrape_configs:
  - job_name: weps-pushgateway
    honor_labels: true
    honor_timestamps: false
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: /metrics
    scheme: http
    file_sd_configs:
      - files:
          - /etc/prometheus/file-sd-dir/weps-pushgateway.yaml
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - 1561-yuk
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: weps-pushgateway-svc
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: http
        action: keep
      - target_label: subsystemId
        replacement: "7568"
        action: replace
      - target_label: subsystemName
        replacement: weps-cluster
        action: replace
    metric_relabel_configs:
      - source_labels: [ test ]
        separator: ;
        regex: weps-keep|aaa|bbb
        action: keep
      - source_labels: [a_mertic]
        separator: ;
        regex: weps-drop|ccc
        action: drop
alerting:
  alert_relabel_configs:
    - regex: prometheus_replica
      action: labeldrop
  alertmanagers:
    - kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - 1561-yuk
      scheme: http
      path_prefix: /
      api_version: v1
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          regex: s-1561-yuk-weps-admintwo-alertmanager-svc
          action: keep
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: web
          action: keep